# Generated by Django 3.2 on 2021-05-18 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floresApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='monbre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='monbre',
            new_name='nombre',
        ),
    ]
